name: Build

on: push

permissions:
  contents: write # Upload artifacts to release
  id-token: write # Use PyPI trusted publishing

env:
  FORCE_COLOR: 1

jobs:
  build:
    name: Build and Inspect
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: hynek/build-and-inspect-python-package@b5076c307dc91924a82ad150cdd1533b444d3310 # v2.12.0

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: publishing
      url: https://pypi.org/p/meltano-tap-hubspot
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: Packages
          path: dist
      - name: Upload wheel to release
        uses: svenstaro/upload-release-action@ebd922b779f285dafcac6410a0710daee9c12b82 # 2.10.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.whl
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Publish
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
